# Generated by Django 5.2.6 on 2025-11-18 13:38

import Conferenceapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conferenceapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(30, 'Vous avez utilisé la limite des mots autorisés')]),
        ),
        migrations.AlterField(
            model_name='organizingcommitee',
            name='date_joined',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='keywords',
            field=models.TextField(validators=[Conferenceapp.models.validate_keywords]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='paper',
            field=models.FileField(upload_to='paper/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Seuls les fichiers PDF sont autorisés.')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('under review', 'under review'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.CharField(default=Conferenceapp.models.generate_submission_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
