# Generated by Django 5.2.6 on 2025-11-18 13:38

import Userapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[Userapp.models.verify_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='ce champs ne doit contenir que des lettres et des espaces', regex='^[a-zA-Z\\s-]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='ce champs ne doit contenir que des lettres et des espaces', regex='^[a-zA-Z\\s-]+$')]),
        ),
    ]
