# Generated by Django 5.2.6 on 2025-11-18 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sessionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Le nom de la salle ne doit contenir que des lettres et des chiffres (sans espaces ni caractères spéciaux).', regex='^[A-Za-z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
